version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sreessj
      POSTGRES_DB: adorable
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data:

